AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  search-lambda

  Sample SAM Template for search-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600

Resources:
  SearchLambdaFunction:
    Type: AWS::Serverless::Function 
    Properties:
      MemorySize: 2048
      PackageType: Image
      Events:
        searchLambda:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /search
            Method: post
    Metadata:
      DockerTag: latest
      DockerContext: ./search-lambda
      Dockerfile: Dockerfile
